config/routes.rb
Clickcounter::Application.routes.draw do
  resources :counters do
    member do
      get 'increment'
    end
  end

  root to:"counters#index"
  
  
end

app/models/counter.rb
class Counter < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/counters_controller.rb
class CountersController < ApplicationController
  before_action :set_counter, only: [:show, :increment]

  # GET /counters/1
  # GET /counters/1.json
  def show
  end
  
  def increment
    @counter.clicks += 1
    @counter.save
    redirect_to counter_path(@counter)
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_counter
      @counter = Counter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def counter_params
      params.require(:counter).permit(:clicks)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counters_helper.rb
module CountersHelper
end

app/views/counters/_form.html.erb
<%= form_for(@counter) do |f| %>
  <% if @counter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@counter.errors.count, "error") %> prohibited this counter from being saved:</h2>

      <ul>
      <% @counter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :clicks %><br>
    <%= f.number_field :clicks %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/counters/edit.html.erb
<h1>Editing counter</h1>

<%= render 'form' %>

<%= link_to 'Show', @counter %> |
<%= link_to 'Back', counters_path %>

app/views/counters/index.html.erb
<h1>Listing counters</h1>

<table>
  <thead>
    <tr>
      <th>Clicks</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @counters.each do |counter| %>
      <tr>
        <td><%= counter.clicks %></td>
        <td><%= link_to 'Show', counter %></td>
        <td><%= link_to 'Edit', edit_counter_path(counter) %></td>
        <td><%= link_to 'Destroy', counter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Counter', new_counter_path %>

app/views/counters/new.html.erb
<h1>New counter</h1>

<%= render 'form' %>

<%= link_to 'Back', counters_path %>

app/views/counters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clicks:</strong>
  <%= @counter.clicks %>
</p>

<%= link_to 'Click me!', increment_counter_path(@counter) %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clickcounter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>